// Generated by CoffeeScript 1.3.3
(function() {

  describe("Calculator", function() {
    var calculator;
    calculator = null;
    beforeEach(function() {
      return calculator = new Calculator;
    });
    it("can add two positive numbers", function() {
      var result;
      result = calculator.add(2, 3);
      return (expect(result)).toBe(5);
    });
    return it("can subtract a negative from a positive", function() {
      var result;
      result = calculator.subtract(4, -6);
      return (expect(result)).toBe(10);
    });
  });

}).call(this);
