// Generated by CoffeeScript 1.3.3
(function() {
  var Calculator;

  window.Calculator = Calculator = (function() {

    function Calculator() {}

    Calculator.prototype.add = function(a, b) {
      return a + b;
    };

    Calculator.prototype.subtract = function(a, b) {
      return a - b;
    };

    return Calculator;

  })();

}).call(this);
